apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 5500
    targetPort: 5500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 10% 
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        imagePullPolicy: Always
        image: stratcastor/duo-backend:latest
        ports:
        - containerPort: 5500

